# reference configuration file: provides project level values
configfile: "config.yml"

# library dependencies
import os

# assigns sample identifiers from config file
SAMPLES = config["SAMPLES"]

# target rule that drives the production of pipeline
rule all:
  input: 
    "raw_fastqc_reports/multiqc_report.html",
    "custom_adapters.fa",
    "overrepresented_sequences.csv",
    "trimmed_fastqc_reports/multiqc_report.html",
    expand("bams/{sample}.sorted.bam", sample = SAMPLES),
    expand("strand/{sample}.strand.txt", sample = SAMPLES),
    "strand_summary.txt",
    "counts.txt",
    "de_analysis/counts_matrix.csv",
    "de_analysis/tpm_counts.csv",
    "de_analysis/basicContrasts_fullDEG_tpm_counts.csv",
    "de_analysis/basicContrasts_sigDEG_tpm_counts.csv",
    "de_analysis/expandedContrastsPADJ_tpm_counts.csv",
    "de_analysis/expandedContrastsL2FC_tpm_counts.csv",
    "de_analysis/expandedContrastsDIRECTION_tpm_counts.csv",
    "de_analysis/expandedContrasts_AllTestData_tpm_counts.csv",


# creates sample level quality reports for automated trimming decisions
rule raw_qc:
  input:
    'raw_fastqs/{sample}.fastq.gz'
  output:
    txt = 'raw_fastqc_reports/{sample}_fastqc/fastqc_data.txt',
    html = 'raw_fastqc_reports/{sample}_fastqc/fastqc_report.html'
  shell:
    """
    #creates output files
    fastqc {input} --extract --outdir raw_fastqc_reports
    rm raw_fastqc_reports/{wildcards.sample}_fastqc.zip
    rm raw_fastqc_reports/{wildcards.sample}_fastqc.html
    """

# creates raw reads aggregated quality report for automated trimming decisions
rule raw_multiqc:
  input:
    expand("raw_fastqc_reports/{sample}_fastqc/fastqc_data.txt", sample = SAMPLES)
  output:
    html = "raw_fastqc_reports/multiqc_report.html"
  shell: 
    """
    multiqc raw_fastqc_reports -o raw_fastqc_reports --force
    """

# generates trim_params.yml that includes call strings for trimming base on raw fastq quality data
rule get_overrep_fa:
  input:
    qc_txts = expand('raw_fastqc_reports/{report}_fastqc/fastqc_data.txt', report = SAMPLES),
  output:
    custom_fa = "custom_adapters.fa",
    overrep_csv = "overrepresented_sequences.csv"
  script: 
    "scripts/generate_overrep_fa.py"

# implements trimming with fastp using the parameters generated by "get_overrep_fa" rule
rule raw_trim:
  input:
    custom_fa = "custom_adapters.fa",
    raw="raw_fastqs/{sample}.fastq.gz",
  output:
    trimmed="trimmed_fastqs/trimmed_{sample}.fastq.gz",
    html = "trimmed_fastp_reports/{sample}_fastp.html",
    json = "trimmed_fastp_reports/{sample}_fastp.json"
  threads: 8
  
  shell:
    """
    fastp -i {input.raw} -o {output.trimmed} \
              --adapter_fasta {input.custom_fa} \
              --trim_poly_g --trim_poly_x \
              --cut_right --cut_right_mean_quality 15 \
              --cut_front --cut_tail \
              -l 50 \
              --html {output.html} \
              --json {output.json} \
              --thread {threads}
    """

# creates sample level quality reports on trimmed data
rule trimmed_qc:
  input:
    'trimmed_fastqs/trimmed_{sample}.fastq.gz'
  output:
    txt = 'trimmed_fastqc_reports/trimmed_{sample}_fastqc/fastqc_data.txt',
    html = 'trimmed_fastqc_reports/trimmed_{sample}_fastqc/fastqc_report.html'
  shell:
    """
    #creates output files
    fastqc {input} --extract --outdir trimmed_fastqc_reports --force
    rm trimmed_fastqc_reports/trimmed_{wildcards.sample}_fastqc.zip
    rm trimmed_fastqc_reports/trimmed_{wildcards.sample}_fastqc.html
    """

# creates aggregate quality check report from trimmed sample level quality reports
rule trimmed_multiqc:
  input:
    expand("trimmed_fastqc_reports/trimmed_{sample}_fastqc/fastqc_data.txt", sample = SAMPLES)
  output:
    html = "trimmed_fastqc_reports/multiqc_report.html",
    per_base = "trimmed_fastqc_reports/multiqc_data/fastqc_per_base_sequence_quality_plot.txt"
  shell: 
    """
    multiqc trimmed_fastqc_reports -o trimmed_fastqc_reports --force
    """


#creates BAM alignment file using HISAT2 software for alignment
rule align_reads:
  input:
    trimmed_fq = "trimmed_fastqs/trimmed_{sample}.fastq.gz",
    index = expand("hisat_index/grch38_tran/genome_tran.{i}.ht2", i=range(1,9)) 
  output: 
    out = "bams/{sample}.sorted.bam"
  params:
     index_prefix = "hisat_index/grch38_tran/genome_tran"
  threads: 8

  shell:
    """
    hisat2 \
      -p {threads} \
      --dta \
      --rna-strandness R \
      -x {params.index_prefix} \
      -U {input.trimmed_fq}| \
  
    samtools sort -@ {threads} -o {output.out}
    samtools index {output.out}
    """
########### Start here: need to establish stranding #####
rule infer_strand:
  input:
    bam = "bams/{sample}.sorted.bam",
    bed = os.path.expanduser(config["REF"]["bed"])
  output:
    "strand/{sample}.strand.txt"
  threads: 2
  shell:
    """
    infer_experiment.py \
      -r {input.bed} \
      -i {input.bam} \
      > {output}
    """

rule summarize_strand:
  input:
    expand("strand/{sample}.strand.txt", sample=SAMPLES)
  output:
    "strand_summary.txt"
  script:
    "scripts/infer_strand.py"
    
# establishes single counts matrix from bam alignment files
rule get_counts:
  input:
    bams = expand("bams/{sample}.sorted.bam", sample = SAMPLES),
    strand = "strand_summary.txt"
  output:
    counts = "counts.txt"
  params:
    ref_genome = config["REF"]["gtf"]
  threads: 2
  run:
    with open(input.strand) as f:
        strand = f.read().strip()

    shell(f"""
    featureCounts \
    -T {threads} \
    -a {params.ref_genome} \
    -t exon \
    -g gene_id \
    -s {strand}\
    -o {output.counts} {' '.join(input.bams)}
    """)
# cleans the sample identifiers and generates version of counts dataframes
rule clean_counts:
  input:
    "counts.txt"
  output:
    "de_analysis/counts_matrix.csv",
    "de_analysis/tpm_counts.csv"
  script:
    "scripts/clean_counts.R"

# establishes experiment's differentially expressed genes
rule basic_differential_expression:
  input:
    "de_analysis/tpm_counts.csv"
  output:
    "de_analysis/basicContrasts_fullDEG_tpm_counts.csv",
    "de_analysis/basicContrasts_sigDEG_tpm_counts.csv"
  script:
    "scripts/DEanalysis_basicContrasts.R"

rule intersectional_differential_expression:
  input:
    "de_analysis/tpm_counts.csv"
  output:
    "de_analysis/expandedContrastsPADJ_tpm_counts.csv",
    "de_analysis/expandedContrastsL2FC_tpm_counts.csv",
    "de_analysis/expandedContrastsDIRECTION_tpm_counts.csv",
    "de_analysis/expandedContrasts_AllTestData_tpm_counts.csv",
  script:
    "scripts/DEanalysis_expandedContrasts.R"