# reference configuration file: provides project level values
configfile: "config.yml"

# library dependencies
import os

# gets dynamically generated trim parameters from yml file
# def load_trim_params():
#   with open ("trim_params.yml") as f:
#     params = yaml.safe_load(f)
#   return params

# assigns sample identifiers from config file
SAMPLES = config["SAMPLES"]

# target rule that drives the production of pipeline
rule all:
  input: 
    "de_analysis/fullDE_tpm_counts.csv",
    "de_analysis/sigDE_tpm_counts.csv",
    "raw_fastqc_reports/multiqc_report.html",
    "trimmed_fastqc_reports/multiqc_report.html"


# creates sample level quality reports for automated trimming decisions
rule raw_qc:
  input:
    'raw_fastqs/{sample}.fastq.gz'
  output:
    txt = 'raw_fastqc_reports/{sample}_fastqc/fastqc_data.txt',
    html = 'raw_fastqc_reports/{sample}_fastqc/fastqc_report.html'
  shell:
    """
    #creates output files
    fastqc {input} --extract --outdir raw_fastqc_reports
    rm raw_fastqc_reports/{wildcards.sample}_fastqc.zip
    rm raw_fastqc_reports/{wildcards.sample}_fastqc.html
    """

# creates raw reads aggregated quality report for automated trimming decisions
rule raw_multiqc:
  input:
    expand("raw_fastqc_reports/{sample}_fastqc/fastqc_data.txt", sample = SAMPLES)
  output:
    html = "raw_fastqc_reports/multiqc_report.html"
  shell: 
    """
    multiqc raw_fastqc_reports -o raw_fastqc_reports --force
    """

# generates trim_params.yml that includes call strings for trimming base on raw fastq quality data
rule get_overrep_fa:
  input:
    qc_txts = expand('raw_fastqc_reports/{report}_fastqc/fastqc_data.txt', report = SAMPLES),
    # multiqc_perbase_seq_qual = 'raw_fastqc_reports/multiqc_data/fastqc_per_base_sequence_quality_plot.txt',
    # multiqc_seq_len = 'raw_fastqc_reports/multiqc_data/fastqc_sequence_length_distribution_plot.txt'
  output:
    # "trim_params.yml"
    custom_fa = "custom_adapters.fa",
    overrep_csv = "overrepresented_sequences.csv"
  # params:
  #   read_type = config["READ_TYPE"]
  script: 
    "scripts/generate_overrep_fa.py"

# implements trimming using the parameters generated by "get_trim_params" rule
rule raw_trim:
  input:
    custom_fa = "custom_adapters.fa",
    raw="raw_fastqs/{sample}.fastq.gz",
  output:
    trimmed="trimmed_fastqs/trimmed_{sample}.fastq.gz",
    html = "trimmed_fastp_reports/{sample}_fastp.html",
    json = "trimmed_fastp_reports/{sample}_fastp.json"
  threads: 8
  
  shell:
    """
    fastp -i {input.raw} -o {output.trimmed} \
              --adapter_fasta {input.custom_fa} \
              --trim_poly_g --trim_poly_x \
              --cut_right --cut_right_mean_quality 15 \
              --cut_front --cut_tail \
              -l 50 \
              --html {output.html} \
              --json {output.json} \
              --thread {threads}
    """


# creates sample level quality reports on trimmed data
rule trimmed_qc:
  input:
    'trimmed_fastqs/trimmed_{sample}.fastq.gz'
  output:
    txt = 'trimmed_fastqc_reports/trimmed_{sample}_fastqc/fastqc_data.txt',
    html = 'trimmed_fastqc_reports/trimmed_{sample}_fastqc/fastqc_report.html'
  shell:
    """
    #creates output files
    fastqc {input} --extract --outdir trimmed_fastqc_reports --force
    rm trimmed_fastqc_reports/trimmed_{wildcards.sample}_fastqc.zip
    rm trimmed_fastqc_reports/trimmed_{wildcards.sample}_fastqc.html
    """

# creates aggregate quality check report from trimmed sample level quality reports
rule trimmed_multiqc:
  input:
    expand("trimmed_fastqc_reports/trimmed_{sample}_fastqc/fastqc_data.txt", sample = SAMPLES)
  output:
    html = "trimmed_fastqc_reports/multiqc_report.html",
    per_base = "trimmed_fastqc_reports/multiqc_data/fastqc_per_base_sequence_quality_plot.txt"
  shell: 
    """
    multiqc trimmed_fastqc_reports -o trimmed_fastqc_reports --force
    """

rule star_index:
  input:
    fasta = os.path.expanduser(config["REF"]["fasta"]),
    gtf   = os.path.expanduser(config["REF"]["gtf"])
  output:
    directory("star_index")
  params:
    index_dir = "star_index"
  threads: 4
  shell:
    """
    mkdir -p {params.index_dir}

    STAR --runThreadN {threads} \
         --runMode genomeGenerate \
         --genomeDir {params.index_dir} \
         --genomeFastaFiles {input.fasta} \
         --sjdbGTFfile {input.gtf} \
         --sjdbOverhang 49
    """

#creates BAM alignment file using STAR software for alignment
rule align_reads:
  input:
    trimmed_fq = "trimmed_fastqs/trimmed_{sample}.fastq.gz",
    index = "star_index"
  output:
    out = "bams/{sample}.sorted.bam"
  threads: 1

  shell:
    """
    STAR --runThreadN {threads} \
         --genomeDir {input.index} \
         --readFilesIn {input.trimmed_fq} \
         --readFilesCommand zcat \
         --outSAMtype BAM SortedByCoordinate \
         --outFilterIntronMotifs RemoveNoncanonical \
         --outFileNamePrefix bams/{wildcards.sample}_

    mv bams/{wildcards.sample}_Aligned.sortedByCoord.out.bam {output.out}
    samtools index {output.out}
    """
########### Start here: need to establish stranding #####
rule infer_strand:
  input:
    bam = "bams/{sample}.sorted.bam",
    bed = os.path.expanduser(config["REF"]["bed"])
  output:
    "strand/{sample}.strand.txt"
  threads: 2
  shell:
    """
    infer_experiment.py \
      -r {input.bed} \
      -i {input.bam} \
      > {output}
    """

rule summarize_strand:
  input:
    expand("strand/{sample}.strand.txt", sample=SAMPLES)
  output:
    "strand_summary.txt"
  script:
    "scripts/infer_strand.py"
    
# establishes single counts matrix from bam alignment files
rule get_counts:
  input:
    bams = expand("bams/{sample}.sorted.bam", sample = SAMPLES),
    strand = "strand_summary.txt"
  output:
    counts = "counts.txt"
  params:
    ref_genome = config["REF"]["gtf"]
  threads: 2
  run:
    with open(input.strand) as f:
        strand = f.read().strip()

    shell(f"""
    featureCounts \
    -T {threads} \
    -a {params.ref_genome} \
    -t exon \
    -g gene_id \
    -s {strand}\
    -M --fraction \
    -o {output.counts} {' '.join(input.bams)}
    """)
# cleans the sample identifiers and generates version of counts dataframes
rule clean_counts:
  input:
    "counts.txt"
  output:
    "de_analysis/counts_matrix.csv",
    "de_analysis/tpm_counts.csv"
  script:
    "scripts/clean_counts.R"

# establishes experiment's differentially expressed genes
rule differential_expression:
  input:
    "de_analysis/tpm_counts.csv"
  output:
    "de_analysis/fullDE_tpm_counts.csv",
    "de_analysis/sigDE_tpm_counts.csv"
  script:
    "scripts/DEanalysis.R"

